#!/bin/sh

CHAT_COMMAND="${0##*/}"

usage() {
    cat >&2 <<EOF
Usage: $CHAT_COMMAND [-sw] [N]

  Emit N (defaults to 5) numbered messages on STDOUT and STDERR after
  emitting an unnumbered startup message and a brief pause. Pauses
  briefly (5ms) before each numbered line of output.

  -s    Copy STDOUT to FD 3
  -w    Wait for a SIGUSR1 before writing, then write without pausing
EOF
}

while getopts ":swh" opt
do
    case "$opt" in
        (s) SAVE=1;;
        (w) WAIT=1;;
        (h) usage
            exit 0;;
        (*) usage
            exit 2;;
    esac
done

shift $((OPTIND - 1))

if [ "$#" -gt 1 ]
then
   usage
   exit 2
elif [ "$#" -eq 1 ]
then
    case "$1" in
        (*[!0-9]*) printf "%s: %s is not a number\n" "$CHAT_COMMAND" "$1"
                   exit 2;;
    esac
    N="$1"
else
    N=5
fi

if [ "$WAIT" ]
then
    pause() {
        if ! [ "$READY" ]
        then
            trap 'READY=1' USR1
            while ! [ "$READY" ]
            do
                sleep 0.001
            done
            trap - USR1
        fi
    }
else
    pause() {
        sleep 0.005
    }
fi

if [ "$SAVE" ]
then
    exec 3>&1
fi

i=0

echo stdout
echo stderr >&2
if [ "$SAVE" ]
then
    echo saved stdout >&3
fi

while [ "$i" -lt "$N" ] && pause
do
    : $((i+=1))
    echo stdout $i
    echo stderr $i >&2
    if [ "$SAVE" ]
    then
        echo saved stdout $i >&3
    fi
done
