#!/bin/sh

CHAT_COMMAND="${0##*/}"

usage() {
    cat >&2 <<EOF
Usage: $CHAT_COMMAND [-s]

  Emit 5 messages on STDOUT and STDERR.

  -s    Copy STDOUT to FD 3
EOF
}

while getopts ":sh" opt
do
    case "$opt" in
        (s) SAVE=1;;
        (h) usage
            exit 0;;
        (*) usage
            exit 2;;
    esac
done

shift $((OPTIND - 1))

if [ "$#" -ne 0 ]
then
   usage
   exit 2
fi

if [ "$SAVE" ]
then
    exec 3>&1
fi

i=0
sleep 0.5
while [ "$i" -lt 5 ]
do
    : $((i+=1))
    echo stdout $i
    echo stderr $i >&2
    if [ "$SAVE" ]
    then
        echo saved stdout $i >&3
    fi
    sleep 0.25
done
