name: Test suite

on:
  pull_request:
  push:
  schedule:
    - cron: '40 13 * * *'

jobs:
  test:
    strategy:
      fail-fast: true

    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get install gdb expect

      - name: Allow unfettered ptrace access
        run: |
          sudo sysctl kernel.yama.ptrace_scope=0
          cat /proc/sys/kernel/yama/ptrace_scope

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Run
        run: |
          ./run_tests.sh

  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          ignore_paths: >-
